#!/bin/bash
[ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"

echo 
echo "----> destroying a Rails app and RVM gemset"
echo 
echo -n "Enter the Rails app name to destroy:"
read APPNAME
rm -rf $APPNAME
rvm gemset delete $APPNAME
echo 
echo "----> $APPNAME deleted." 