#!/bin/bash
echo
echo -n "Create a new Rails 4.0.2 app?(y/n): "

# Continue?
read CONTNEW
if [ "$CONTNEW" = "n" ]
  then
  echo
  echo "----> RailsBricks exited."
  exit 1
fi

# App name
echo 
echo -n "What do you want to call your app?: " 
read APPNAME

# User model
echo
echo "USER MODEL:"
echo "-----------"
echo "1) Simple"
echo "2) Devise"
echo "3) None"
echo -n "(1), (2), (3): "
read USERMODEL

# Layout
echo 
echo "LAYOUT:"
echo "-------------------"
echo "1) Reset CSS"
echo "2) Bootstrap 3 SASS"
echo -n "(1)/(2): "
read LAYOUT

# Env variables 
echo
echo "ENVIRONMENT VARIABLES:"
echo "----------------------"
echo "Enter the production domain"
echo "(example: www.example.com, app.example.com, ...)"
echo -n ": "
read DOMAIN

echo 
echo "Enter the mailer domain"
echo "(example: example.com)"
echo -n ": "
read MAILERDOMAIN

echo 
echo "Enter the SMTP server"
echo "(example: mail.example.com)"
echo -n ": "
read SMTPSERVER

echo 
echo -n "Enter the SMTP port: "
read SMTPPORT

echo 
echo -n "Enter the SMTP username: "
read SMTPUSER

echo
echo -n "Enter the SMTP password?: "
read SMTPPWD

echo
echo -n "Which email address to send mail from?: "
read SENDEREMAIL

# Git
echo
echo "GIT CONFIG:"
echo "----------------------------"
echo -n "Init a Git repository?(y/n): "
read GITSET

# Remote Git
if [ "$GITSET" = "y" ]
  then
  echo
  echo -n "Set a remote Git repository?(y/n): "
  read GITREMOTE
  
  if [ "$GITREMOTE" = "y" ]
    then
    echo
    echo "Remote Git repository URL?"
    echo "(example: https://my-name@bitbucket.org/my-name/my-app.git)"
    echo -n ": "
    read GITREMOTEURL
  fi  
fi

# Confirmation
echo
echo "----> User input set."

# RVM
echo
echo "----> Creating RVM Gemset ..."
[ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"
rvm use 2.0.0@$APPNAME --create
echo
echo "----> RVM Gemset created."

# Rails 4.0.2
echo
echo "----> Installing Rails 4.0.2 into Gemset $APPNAME ..."
gem install rails -v 4.0.2
echo
echo "----> Rails 4.0.2 installed."

# Create app
echo
echo "----> Creating $APPNAME ..."
rails new $APPNAME --skip-bundle
echo
echo "----> $APPNAME created."

# cd into app
cd "$APPNAME"

# Set rvmrc
echo
echo "----> Setting .rvmrc ..."
rvm --rvmrc 2.0.0@$APPNAME
echo
echo "----> .rvmrc set."

# Set Gemfile
echo
echo "----> Setting Gemfile ..."
rm Gemfile
cp ~/railsbricks/assets/gemfile/Gemfile_simple Gemfile
~/railsbricks/assets/gemfile/set_gemfile.rb $USERMODEL $LAYOUT
echo
echo "----> Gemfile set."

# Bundle install (no prod)
echo 
echo "----> Installing Gems ..."
bundle install --without production
echo 
echo "----> Gems installed."

# Config Gems (kaminari, figaro & friendly_id)
echo
echo "----> Kaminari config ..."
rails generate kaminari:config
echo
echo "----> Kaminari set."

echo
echo "----> Figaro config ..."
rails generate figaro:install
echo
echo "----> Figaro set."

echo 
echo "----> Friendly_id config ..."
rails generate friendly_id
echo
echo "----> Friendly_id set."

# Rails layout if Bootstrap 3
if [ "$LAYOUT" = "2" ]
  then
  echo
  echo "----> Generating Bootstrap 3 layout ..."
  rails generate layout bootstrap3 --force
  echo
  echo "----> Bootstrap 3 layout generated"  
fi

# Devise install if option set
if [ "$USERMODEL" = "2" ]
  then
  echo 
  echo "----> Setting Devise ..."
  rails generate devise:install
  echo
  echo "----> Devise set."
fi

# Add a date_format initializer
echo
echo "----> Adding a date_format initializer ..."
cp ~/railsbricks/assets/date_format/date_format.rb config/initializers/date_format.rb
echo 
echo "----> date_format.rb initializer set."

# Configure application.yml
echo 
echo "----> Setting application.yml ..."
rm config/application.yml
~/railsbricks/assets/figaro/set_figaro.rb $DOMAIN $MAILERDOMAIN $SMTPUSER $SMTPPWD $SENDEREMAIL $SMTPSERVER $SMTPPORT
echo
echo "----> application.yml set."

# Secret token
echo 
echo "----> Setting secret_token.rb ..."
rm config/initializers/secret_token.rb
~/railsbricks/assets/secret_token/set_secret_token.rb $APPNAME
echo
echo "----> secret_token.rb set."

# Environments mailers (dev+prod)
echo
echo "----> Setting Environments configs ..."
rm config/environments/development.rb
rm config/environments/production.rb
~/railsbricks/assets/environments/set_environments.rb $APPNAME
echo
echo "----> Environments config set."

# Create the user model
if [ "$USERMODEL" = "1" ]
  then 
  echo
  echo "----> Setting Simple User model ..."
  rails g model User username email password_digest admin:boolean slug
  ~/railsbricks/assets/user_model/simple/set_user.rb
  
  rm app/controllers/application_controller.rb
  cp ~/railsbricks/assets/user_model/simple/application_controller.rb app/controllers/application_controller.rb
  
  rm app/models/user.rb
  cp ~/railsbricks/assets/user_model/simple/user.rb app/models/user.rb
  echo
  echo "----> Simple User model set."
elif [ "$USERMODEL" = "2" ]
  then
  echo
  echo "----> Setting Devise User model ..."
  rails g devise User
  ~/railsbricks/assets/user_model/devise/set_user.rb
  
  rm app/controllers/application_controller.rb
  cp ~/railsbricks/assets/user_model/devise/application_controller.rb app/controllers/application_controller.rb
  
  rm app/models/user.rb
  cp ~/railsbricks/assets/user_model/devise/user.rb app/models/user.rb
  
  rm config/initializers/devise.rb
  cp ~/railsbricks/assets/user_model/devise/devise.rb config/initializers/devise.rb
  echo
  echo "----> Devise User model set."
else
  echo
  echo "----> No User model to generate."
fi

# Create User seed data 
if [ "$USERMODEL" = "1" ]
  then
  echo
  echo "----> Creating seed data for Simple User Model ..."
  rm db/seeds.rb
  cp ~/railsbricks/assets/seed/simple/seeds.rb db/seeds.rb
  echo
  echo "----> seed data for Simple User Model created."
elif [ "$USERMODEL" = "2" ]
  then
  echo
  echo "----> Creating seed data for Devise User Model ..."
  rm db/seeds.rb
  cp ~/railsbricks/assets/seed/devise/seeds.rb db/seeds.rb
  echo
  echo "----> seed data for Devise User Model created."
else
  echo
  echo "----> No seed data necessary."
fi

# Updates application.rb
echo 
echo "----> Updating application.rb ..."
rm config/application.rb
~/railsbricks/assets/application/set_application.rb $APPNAME
echo
echo "----> application.rb set."

# Set favicon
echo
echo "----> Setting favicon ..."
cp ~/railsbricks/assets/bricks/common/images/favicon.ico app/assets/images/favicon.ico

# *************************************************************
# BRICKS

# No auth, reset CSS : none-reset
if [ "$USERMODEL" = "3" ] && [ "$LAYOUT" = "1" ]
  then
  echo
  echo "----> BRICKS: No authentication, reset CSS <----"

  echo
  echo "---> Overriding default CSS ..."
  rm app/assets/stylesheets/application.css
  cp ~/railsbricks/assets/bricks/common/css/reset/application.css.scss app/assets/stylesheets/application.css.scss
  echo
  echo "---> application.css.scss set."
  
  echo
  echo "---> Creating Pages controller ..."
  cp ~/railsbricks/assets/bricks/common/controllers/pages_controller.rb app/controllers/pages_controller.rb
  echo
  echo "---> Pages controller created."
  
  echo
  echo "---> Updating application_helper.rb ..."
  rm app/helpers/application_helper.rb
  ~/railsbricks/assets/bricks/common/helpers/set_application_helper.rb $APPNAME
  echo
  echo "---> application_helper set."
  
  echo
  echo "---> Updating application.html.erb"
  rm app/views/layouts/application.html.erb
  ~/railsbricks/assets/bricks/common/layouts/reset/set_application.rb $APPNAME
  echo
  echo "---> application.html.erb set"
  
  echo 
  echo "---> Creating flash messages partial ..."
  cp ~/railsbricks/assets/bricks/common/layouts/reset/_messages.html.erb app/views/layouts/_messages.html.erb
  echo
  echo "---> Flash messages partial created."
  
  echo
  echo "---> Creating Home view ..."
  mkdir app/views/pages
  cp ~/railsbricks/assets/bricks/none-reset/views/home.html.erb app/views/pages/home.html.erb
  echo
  echo "---> Home view created."
  
  echo
  echo "---> Updating routes.rb"
  rm config/routes.rb
  ~/railsbricks/assets/bricks/common/routes/none/set_routes.rb $APPNAME
  echo
  echo "---> routes.rb updated."
  
  echo
  echo "----> BRICKS: selected brick generated."
fi

# No auth, bootstrap : none-bootstrap
if [ "$USERMODEL" = "3" ] && [ "$LAYOUT" = "2" ]
  then
  echo
  echo "----> BRICKS: No authentication, Bootstrap 3 <----"
  
  echo
  echo "---> Overriding default CSS ..."
  rm app/assets/stylesheets/application.css.scss
  cp ~/railsbricks/assets/bricks/common/css/bootstrap/application.css.scss app/assets/stylesheets/application.css.scss
  rm app/assets/stylesheets/framework_and_overrides.css.scss
  cp ~/railsbricks/assets/bricks/none-bootstrap/css/framework_and_overrides.css.scss app/assets/stylesheets/framework_and_overrides.css.scss
  echo
  echo "---> Default CSS set."
  
  echo
  echo "---> Creating Pages controller ..."
  cp ~/railsbricks/assets/bricks/common/controllers/pages_controller.rb app/controllers/pages_controller.rb
  echo
  echo "---> Pages controller created."
  
  echo
  echo "---> Updating application_helper.rb ..."
  rm app/helpers/application_helper.rb
  ~/railsbricks/assets/bricks/common/helpers/set_application_helper.rb $APPNAME
  echo
  echo "---> application_helper set."
  
  echo
  echo "---> Updating routes.rb"
  rm config/routes.rb
  ~/railsbricks/assets/bricks/common/routes/none/set_routes.rb $APPNAME
  echo
  echo "---> routes.rb updated."
  
  echo
  echo "---> Creating Home view ..."
  mkdir app/views/pages
  cp ~/railsbricks/assets/bricks/none-bootstrap/views/home.html.erb app/views/pages/home.html.erb
  echo
  echo "---> Home view created."
  
  echo
  echo "---> Updating application.html.erb"
  rm app/views/layouts/application.html.erb
  ~/railsbricks/assets/bricks/common/layouts/bootstrap/set_application.rb $APPNAME
  echo
  echo "---> application.html.erb set."
  
  echo
  echo "---> Creating a footer ..."
  cp ~/railsbricks/assets/bricks/common/layouts/bootstrap/_footer.html.erb app/views/layouts/_footer.html.erb
  echo
  echo "---> Footer created."
  
  echo
  echo "---> Updating navigation ..."
  rm app/views/layouts/_navigation_links.html.erb
  rm app/views/layouts/_navigation.html.erb
  cp ~/railsbricks/assets/bricks/none-bootstrap/views/_navigation_links.html.erb app/views/layouts/_navigation_links.html.erb
  cp ~/railsbricks/assets/bricks/none-bootstrap/views/_navigation.html.erb app/views/layouts/_navigation.html.erb
  echo
  echo "---> Navigation updated."
  
  echo
  echo "----> BRICKS: selected brick generated."
fi

# auth simple, reset CSS : simple-reset
if [ "$USERMODEL" = "1" ] && [ "$LAYOUT" = "1" ]
  then
  echo
  echo "----> BRICKS: Simple authentication, reset CSS <----"
  
  echo
  echo "---> Overriding default CSS ..."
  rm app/assets/stylesheets/application.css
  cp ~/railsbricks/assets/bricks/common/css/reset/application.css.scss app/assets/stylesheets/application.css.scss
  echo
  echo "---> application.css.scss set."
  
  echo
  echo "---> Creating Pages controller ..."
  cp ~/railsbricks/assets/bricks/common/controllers/pages_controller.rb app/controllers/pages_controller.rb
  echo
  echo "---> Pages controller created."
  
  echo
  echo "---> Updating application_helper.rb ..."
  rm app/helpers/application_helper.rb
  ~/railsbricks/assets/bricks/common/helpers/set_application_helper.rb $APPNAME
  echo
  echo "---> application_helper set."
  
  echo
  echo "---> Updating routes.rb"
  rm config/routes.rb
  ~/railsbricks/assets/bricks/common/routes/simple/set_routes.rb $APPNAME
  echo
  echo "---> routes.rb updated."
  
  echo
  echo "---> Creating Sign in view ..."
  mkdir app/views/sessions
  cp ~/railsbricks/assets/bricks/simple-reset/views/sessions/new.html.erb app/views/sessions/new.html.erb
  echo
  echo "---> Sign in view created."
  
  echo
  echo "---> Creating Sessions controller ..."
  cp ~/railsbricks/assets/bricks/common/controllers/simple/sessions_controller.rb app/controllers/sessions_controller.rb
  echo
  echo "---> Sessions controller created."
  
  echo
  echo "---> Updating application.html.erb"
  rm app/views/layouts/application.html.erb
  ~/railsbricks/assets/bricks/common/layouts/reset/set_application.rb $APPNAME
  echo
  echo "---> application.html.erb set"
  
  echo 
  echo "---> Creating flash messages partial ..."
  cp ~/railsbricks/assets/bricks/common/layouts/reset/_messages.html.erb app/views/layouts/_messages.html.erb
  echo
  echo "---> Flash messages partial created."
  
  echo
  echo "---> Creating Home page ..."
  mkdir app/views/pages
  cp ~/railsbricks/assets/bricks/simple-reset/views/pages/home.html.erb app/views/pages/home.html.erb
  echo
  echo "---> Home page created."
  
  echo
  echo "---> Creating Admin controllers ..."
  mkdir app/controllers/admin
  cp ~/railsbricks/assets/bricks/common/controllers/simple/admin/base_controller.rb app/controllers/admin/base_controller.rb
  cp ~/railsbricks/assets/bricks/common/controllers/simple/admin/users_controller.rb app/controllers/admin/users_controller.rb
  echo
  echo "---> Admin controllers created."
  
  echo 
  echo "---> Creating Admin views ..."
  mkdir app/views/admin
  mkdir app/views/admin/base
  mkdir app/views/admin/users
  cp ~/railsbricks/assets/bricks/simple-reset/views/admin/base/index.html.erb app/views/admin/base/index.html.erb
  cp ~/railsbricks/assets/bricks/simple-reset/views/admin/users/edit.html.erb app/views/admin/users/edit.html.erb
  echo
  echo "---> Admin views created."
  
  echo
  echo "----> BRICKS: selected brick generated."
fi

# auth simple, bootstrap : simple-bootstrap
if [ "$USERMODEL" = "1" ] && [ "$LAYOUT" = "2" ]
  then
  echo
  echo "----> BRICKS: Simple authentication, Bootstrap 3 <----"
  
  echo
  echo "---> Overriding default CSS ..."
  rm app/assets/stylesheets/application.css.scss
  cp ~/railsbricks/assets/bricks/common/css/bootstrap/application.css.scss app/assets/stylesheets/application.css.scss
  rm app/assets/stylesheets/framework_and_overrides.css.scss
  cp ~/railsbricks/assets/bricks/simple-bootstrap/css/framework_and_overrides.css.scss app/assets/stylesheets/framework_and_overrides.css.scss
  echo
  echo "---> Default CSS set."
  
  echo
  echo "---> Creating Pages controller ..."
  cp ~/railsbricks/assets/bricks/common/controllers/pages_controller.rb app/controllers/pages_controller.rb
  echo
  echo "---> Pages controller created."
  
  echo
  echo "---> Updating application_helper.rb ..."
  rm app/helpers/application_helper.rb
  ~/railsbricks/assets/bricks/common/helpers/set_application_helper.rb $APPNAME
  echo
  echo "---> application_helper set."
  
  echo
  echo "---> Updating routes.rb"
  rm config/routes.rb
  ~/railsbricks/assets/bricks/common/routes/simple/set_routes.rb $APPNAME
  echo
  echo "---> routes.rb updated."
  
  echo
  echo "---> Creating Admin controllers ..."
  mkdir app/controllers/admin
  cp ~/railsbricks/assets/bricks/common/controllers/simple/admin/base_controller.rb app/controllers/admin/base_controller.rb
  cp ~/railsbricks/assets/bricks/common/controllers/simple/admin/users_controller.rb app/controllers/admin/users_controller.rb
  echo
  echo "---> Admin controllers created."
  
  echo
  echo "---> Creating Sessions controller ..."
  cp ~/railsbricks/assets/bricks/common/controllers/simple/sessions_controller.rb app/controllers/sessions_controller.rb
  echo
  echo "---> Sessions controller created."
  
  echo
  echo "---> Updating application.html.erb"
  rm app/views/layouts/application.html.erb
  ~/railsbricks/assets/bricks/common/layouts/bootstrap/set_application.rb $APPNAME
  echo
  echo "---> application.html.erb set."
  
  echo
  echo "---> Creating a footer ..."
  cp ~/railsbricks/assets/bricks/common/layouts/bootstrap/_footer.html.erb app/views/layouts/_footer.html.erb
  echo
  echo "---> Footer created."
  
  echo
  echo "---> Updating navigation ..."
  rm app/views/layouts/_navigation_links.html.erb
  rm app/views/layouts/_navigation.html.erb
  cp ~/railsbricks/assets/bricks/simple-bootstrap/views/layouts/_navigation_links.html.erb app/views/layouts/_navigation_links.html.erb
  cp ~/railsbricks/assets/bricks/simple-bootstrap/views/layouts/_navigation.html.erb app/views/layouts/_navigation.html.erb
  echo
  echo "---> Navigation updated."
  
  echo
  echo "---> Creating Home page ..."
  mkdir app/views/pages
  cp ~/railsbricks/assets/bricks/simple-bootstrap/views/pages/home.html.erb app/views/pages/home.html.erb
  echo
  echo "---> Home page created."
  
  echo
  echo "---> Creating Sign in page ..."
  mkdir app/views/sessions
  cp ~/railsbricks/assets/bricks/simple-bootstrap/views/sessions/new.html.erb app/views/sessions/new.html.erb
  echo
  echo "---> Sign in page created."
  
  echo 
  echo "---> Creating Admin views ..."
  mkdir app/views/admin
  mkdir app/views/admin/base
  mkdir app/views/admin/users
  cp ~/railsbricks/assets/bricks/simple-bootstrap/views/admin/base/index.html.erb app/views/admin/base/index.html.erb
  cp ~/railsbricks/assets/bricks/simple-bootstrap/views/admin/users/edit.html.erb app/views/admin/users/edit.html.erb
  echo
  echo "---> Admin views created."
  
  echo
  echo "----> BRICKS: selected brick generated."
fi

# auth devise, reset CSS : devise-reset
if [ "$USERMODEL" = "2" ] && [ "$LAYOUT" = "1" ]
  then
  echo
  echo "----> BRICKS: Devise authentication, reset CSS <----"
  
  echo
  echo "---> Overriding default CSS ..."
  rm app/assets/stylesheets/application.css
  cp ~/railsbricks/assets/bricks/common/css/reset/application.css.scss app/assets/stylesheets/application.css.scss
  echo
  echo "---> application.css.scss set."
  
  echo
  echo "---> Updating application.html.erb"
  rm app/views/layouts/application.html.erb
  ~/railsbricks/assets/bricks/common/layouts/reset/set_application.rb $APPNAME
  echo
  echo "---> application.html.erb set"
  
  echo 
  echo "---> Creating flash messages partial ..."
  cp ~/railsbricks/assets/bricks/common/layouts/reset/_messages.html.erb app/views/layouts/_messages.html.erb
  echo
  echo "---> Flash messages partial created."
  
  echo
  echo "---> Updating application_helper.rb ..."
  rm app/helpers/application_helper.rb
  ~/railsbricks/assets/bricks/common/helpers/set_application_helper.rb $APPNAME
  echo
  echo "---> application_helper set."
  
  echo
  echo "---> Creating Admin controllers ..."
  mkdir app/controllers/admin
  cp ~/railsbricks/assets/bricks/common/controllers/devise/admin/base_controller.rb app/controllers/admin/base_controller.rb
  cp ~/railsbricks/assets/bricks/common/controllers/devise/admin/users_controller.rb app/controllers/admin/users_controller.rb
  echo
  echo "---> Admin controllers created."
  
  echo
  echo "---> Creating views ..."
  mkdir app/views/pages
  cp ~/railsbricks/assets/bricks/devise-reset/views/pages/home.html.erb app/views/pages/home.html.erb
  cp ~/railsbricks/assets/bricks/devise-reset/views/pages/inside.html.erb app/views/pages/inside.html.erb
  echo
  echo "---> Views created."

  echo
  echo "---> Creating Admin views ..."
  mkdir app/views/admin
  mkdir app/views/admin/base
  mkdir app/views/admin/users
  cp ~/railsbricks/assets/bricks/devise-reset/views/admin/base/index.html.erb app/views/admin/base/index.html.erb
  cp ~/railsbricks/assets/bricks/devise-reset/views/admin/users/index.html.erb app/views/admin/users/index.html.erb
  cp ~/railsbricks/assets/bricks/devise-reset/views/admin/users/edit.html.erb app/views/admin/users/edit.html.erb
  echo
  echo "---> Admin views created."
  
  echo
  echo "---> Updating routes.rb"
  rm config/routes.rb
  ~/railsbricks/assets/bricks/common/routes/devise/set_routes.rb $APPNAME
  echo
  echo "---> routes.rb updated."
  
  echo
  echo "---> Creating a Pages controller ..."
  cp ~/railsbricks/assets/bricks/common/controllers/devise/pages_controller.rb app/controllers/pages_controller.rb
  echo
  echo "---> Pages controller created."
  
  echo
  echo "---> Creating Devise views ..."
  mkdir app/views/devise
  mkdir app/views/devise/confirmations
  mkdir app/views/devise/mailer
  mkdir app/views/devise/passwords
  mkdir app/views/devise/registrations
  mkdir app/views/devise/sessions
  mkdir app/views/devise/shared
  
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/confirmations/new.html.erb app/views/devise/confirmations/new.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/mailer/confirmation_instructions.html.erb app/views/devise/mailer/confirmation_instructions.html.erb
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/mailer/reset_password_instructions.html.erb app/views/devise/mailer/reset_password_instructions.html.erb
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/mailer/unlock_instructions.html.erb app/views/devise/mailer/unlock_instructions.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/passwords/new.html.erb app/views/devise/passwords/new.html.erb
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/passwords/edit.html.erb app/views/devise/passwords/edit.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/registrations/edit.html.erb app/views/devise/registrations/edit.html.erb
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/registrations/new.html.erb app/views/devise/registrations/new.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/sessions/new.html.erb app/views/devise/sessions/new.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-reset/views/devise/shared/_links.erb app/views/devise/shared/_links.erb
  echo
  echo "---> Devise views created."
  
  echo
  echo "----> BRICKS: selected brick generated."
fi

# auth devise, bootstrap : devise-bootstrap
if [ "$USERMODEL" = "2" ] && [ "$LAYOUT" = "2" ]
  then
  echo
  echo "----> BRICKS: Devise authentication, Bootstrap 3 <----"
  
  echo
  echo "---> Overriding default CSS ..."
  rm app/assets/stylesheets/application.css.scss
  cp ~/railsbricks/assets/bricks/common/css/bootstrap/application.css.scss app/assets/stylesheets/application.css.scss
  rm app/assets/stylesheets/framework_and_overrides.css.scss
  cp ~/railsbricks/assets/bricks/devise-bootstrap/css/framework_and_overrides.css.scss app/assets/stylesheets/framework_and_overrides.css.scss
  echo
  echo "---> Default CSS set."
  
  echo
  echo "---> Creating Admin controllers ..."
  mkdir app/controllers/admin
  cp ~/railsbricks/assets/bricks/common/controllers/devise/admin/base_controller.rb app/controllers/admin/base_controller.rb
  cp ~/railsbricks/assets/bricks/common/controllers/devise/admin/users_controller.rb app/controllers/admin/users_controller.rb
  echo
  echo "---> Admin controllers created."
  
  echo
  echo "---> Creating a Pages controller ..."
  cp ~/railsbricks/assets/bricks/common/controllers/devise/pages_controller.rb app/controllers/pages_controller.rb
  echo
  echo "---> Pages controller created."
  
  echo
  echo "---> Updating application_helper.rb ..."
  rm app/helpers/application_helper.rb
  ~/railsbricks/assets/bricks/common/helpers/set_application_helper.rb $APPNAME
  echo
  echo "---> application_helper set."
  
  echo
  echo "---> Updating application.html.erb"
  rm app/views/layouts/application.html.erb
  ~/railsbricks/assets/bricks/common/layouts/bootstrap/set_application.rb $APPNAME
  echo
  echo "---> application.html.erb set."
  
  echo
  echo "---> Creating a footer ..."
  cp ~/railsbricks/assets/bricks/common/layouts/bootstrap/_footer.html.erb app/views/layouts/_footer.html.erb
  echo
  echo "---> Footer created."
  
  echo
  echo "---> Updating navigation ..."
  rm app/views/layouts/_navigation_links.html.erb
  rm app/views/layouts/_navigation.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/layouts/_navigation_links.html.erb app/views/layouts/_navigation_links.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/layouts/_navigation.html.erb app/views/layouts/_navigation.html.erb
  echo
  echo "---> Navigation updated."
  
  echo
  echo "---> Updating routes.rb"
  rm config/routes.rb
  ~/railsbricks/assets/bricks/common/routes/devise/set_routes.rb $APPNAME
  echo
  echo "---> routes.rb updated."
  
  echo
  echo "---> Creating Admin views ..."
  mkdir app/views/admin
  mkdir app/views/admin/base
  mkdir app/views/admin/users
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/admin/base/index.html.erb app/views/admin/base/index.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/admin/users/index.html.erb app/views/admin/users/index.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/admin/users/edit.html.erb app/views/admin/users/edit.html.erb
  echo
  echo "---> Admin views created."
  
  echo
  echo "---> Creating views ..."
  mkdir app/views/pages
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/pages/home.html.erb app/views/pages/home.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/pages/inside.html.erb app/views/pages/inside.html.erb
  echo
  echo "---> Views created."
  
  echo
  echo "---> Creating Devise views ..."
  mkdir app/views/devise
  mkdir app/views/devise/confirmations
  mkdir app/views/devise/mailer
  mkdir app/views/devise/passwords
  mkdir app/views/devise/registrations
  mkdir app/views/devise/sessions
  mkdir app/views/devise/shared
  
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/confirmations/new.html.erb app/views/devise/confirmations/new.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/mailer/confirmation_instructions.html.erb app/views/devise/mailer/confirmation_instructions.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/mailer/reset_password_instructions.html.erb app/views/devise/mailer/reset_password_instructions.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/mailer/unlock_instructions.html.erb app/views/devise/mailer/unlock_instructions.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/passwords/new.html.erb app/views/devise/passwords/new.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/passwords/edit.html.erb app/views/devise/passwords/edit.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/registrations/edit.html.erb app/views/devise/registrations/edit.html.erb
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/registrations/new.html.erb app/views/devise/registrations/new.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/sessions/new.html.erb app/views/devise/sessions/new.html.erb
  
  cp ~/railsbricks/assets/bricks/devise-bootstrap/views/devise/shared/_links.erb app/views/devise/shared/_links.erb
  echo
  echo "---> Devise views created."
  
  echo
  echo "----> BRICKS: selected brick generated."
fi

# END BRICKS
# *************************************************************
  
# Migrating DB
echo
echo "----> Initializing the database ..."
rake db:migrate
rake db:seed
echo
echo "----> Database initialized."

# Git
if [ "$GITSET" = "y" ]
  then
  echo
  echo "----> Setting .gitignore ..."
  rm .gitignore
  cp ~/railsbricks/assets/gitignore/gitignore .gitignore
  echo 
  echo "----> .gitignore set."
  
  echo
  echo "----> Initializing Git repository ..."
  git init
  git add -A .
  git commit -m "initial commit (generated by RailsBricks)"
  echo
  echo "----> Local Git repository set."
  
  if [ "$GITREMOTE" = "y" ]
    then
    echo
    echo "----> Setting remote repository ..."
    git remote add origin $GITREMOTEURL
    git push origin master
    echo
    echo "----> Local master branch pushed to origin."
  fi  
fi

# Confirm
echo
echo
echo "************************************************"
echo " RailsBricks generated your app: $APPNAME"
echo
if [ "$USERMODEL" = "1" ] || [ "$USERMODEL" = "2" ]
  then
  echo " Default admin account"
  echo " ---------------------"
  echo " Username: admin"
  echo " Password: 1234"
  echo
fi
echo " http://www.railsbricks.net"
echo "************************************************"
echo
echo "Have a great coding time!"
echo
