#!/bin/bash

echo 
echo "----> Getting latest version from Github ..."
echo 
cd ~/railsbricks/
git pull https://github.com/nicoschuele/railsbricks.git
echo
echo "----> RailsBricks is up to date." 
echo