#!/bin/bash
if [ "$1" = "-n" ] || [ "$1" = "--new" ]
  then
  rails_create
elif [ "$1" = "-D" ] || [ "$1" = "--destroy" ]
  then
  rails_destroy
elif [ "$1" = "-r" ] || [ "$1" = "--recreate-db" ]
  then
  rails_db_recreate
elif [ "$1" = "-v" ] || [ "$1" = "--versions" ]
  then
  echo
  echo "RailsBricks 1.1.0 (stable) by Nico Schuele <nico@railsbricks.net>"
  echo "http://www.railsbricks.net"
  echo
elif [ "$1" = "--update" ]
  then
  rbricks_update
  
else

  echo
  echo
  echo "************************************************"
  echo "*             RailsBricks v1.1.0               *"
  echo "*             ------------------               *"
  echo "*         http://www.railsbricks.net           *"
  echo "************************************************"
  echo
  echo "1) Create a new Rails app"
  echo "2) Recreate database"
  echo "3) Shortcuts"
  echo "4) Update RailsBricks"
  echo "5) Exit"
  echo -n ": "
  read CHOICE
  
  if [ "$CHOICE" = "1" ]
    then
    rails_create
  elif [ "$CHOICE" = "2" ]
    then
    rails_db_recreate
  elif [ "$CHOICE" = "3" ]
    then
    echo
    echo "rbricks -n (or rbricks --new):" 
    echo " - creates a new Rails app with RailsBricks templates"
    echo "rbricks -r (or rbricks --recreate-db):" 
    echo " - drop, migrate and seed the development database"
    echo "rbricks --update:" 
    echo " - updates RailsBricks to the latest version"
    echo
  elif [ "$CHOICE" = "4" ]
    then
    rbricks_update
  else
    exit 1
  fi

fi