#!/bin/bash
if [ "$1" = "-n" ] || [ "$1" = "--new" ]
  then
  rails_create
elif [ "$1" = "-D" ] || [ "$1" = "--destroy" ]
  then
  rails_destroy
elif [ "$1" = "-r" ] || [ "$1" = "--recreate-db" ]
  then
  rails_db_recreate
elif [ "$1" = "-v" ] || [ "$1" = "--versions" ]
  then
  echo
  echo "RailsBricks 1.0.1 (stable) by Nico Schuele <nico@railsbricks.net>"
  echo "http://www.railsbricks.net"
  echo
else

  echo
  echo
  echo "************************************************"
  echo "*             RailsBricks v1.0.2               *"
  echo "*             ------------------               *"
  echo "*         http://www.railsbricks.net           *"
  echo "************************************************"
  echo
  echo "1) Create a new Rails app"
  echo "2) Destroy a Rails app"
  echo "3) Recreate database"
  echo "4) Shortcuts"
  echo "5) Exit"
  echo -n ": "
  read CHOICE
  
  if [ "$CHOICE" = "1" ]
    then
    rails_create
  elif [ "$CHOICE" = "2" ]
    then
    rails_destroy
  elif [ "$CHOICE" = "3" ]
    then
    rails_db_recreate
  elif [ "$CHOICE" = "4" ]
    then
    echo
    echo "rbricks -n (or rbricks --new):" 
    echo " - creates a new Rails app with RailsBricks templates"
    echo "rbricks -D (or rbricks --destroy):"     
    echo " - destroys a Rails app and its RVM gemset"
    echo "rbricks -r (or rbricks --recreate-db):" 
    echo " - drop, migrate and seed the development database"
    echo
  else
    exit 1
  fi

fi