source 'https://rubygems.org'
ruby 'RUBYVERSION'
gem 'rails', '4.1.6'
gem 'sass-rails', '4.0.3'
gem 'uglifier', '2.5.3'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.1.2'
gem 'turbolinks', '2.3.0'
gem 'jbuilder', '2.1.3'
gem 'bcrypt', '3.1.7'

group :doc do
  gem 'sdoc', require: false
end

# development gems
group :development, :test do
  gem 'sqlite3', '1.3.9'    # dev & test database
  gem 'figaro', '0.7.0'     # env variables
end

# Paging
gem 'kaminari', '0.16.1'

# Slugs and friendly id's
gem 'friendly_id', '5.0.4'

# font-awesome
gem 'font-awesome-sass', '4.2.0'